### ISSUE TITLE
Group by question

### ISSUE THREAD

**Issue by hennaboy** [msbatal/PHP-PDO-Database-Class#1]
This is my query

$select = $db->select('sales_tbl', ['sum(total) as total', 'count(*) as count', 'hour(createdAt) as label'])
->where('createdAt', 'DATE_SUB(CURDATE(), INTERVAL 24 HOUR', '>=')
->groupBy('createdAt')
->run();

I need to group by HOUR('createdAt') but it seems not possible?

**Comment by msbatal** [comment]
Repo updated. You can use all functions in "Group By" method. Don't forget to define the function as the second parameter.

$select = $db->select('tableName')
             ->groupBy('column', 'DAYNAME')
             ->run();
// Gives: SELECT * FROM tableName GROUP BY DAYNAME(column);

**Comment by hennaboy** [comment]
You are perhaps aware this is not working as intended. 

Result from the code as stated
Array ( [0] => Array ( [total] => 6.200000047683716 [count] => 4 [label] => 2 ) [1] => Array ( [total] => 3.600000023841858 [count] => 2 [label] => 7 ) [2] => Array ( [total] => 21.09000015258789 [count] => 7 [label] => 8 ) [3] => Array ( [total] => 195060.48070669174 [count] => 2231 [label] => 9 ) [4] => Array ( [total] => 20055.539966657758 [count] => 4549 [label] => 10 ) [5] => Array ( [total] => 33460.53993752226 [count] => 8200 [label] => 11 ) [6] => Array ( [total] => 43840.6998969987 [count] => 10860 [label] => 12 ) [7] => Array ( [total] => 54296.409831445664 [count] => 13785 [label] => 13 ) [8] => Array ( [total] => 65521.63976806775 [count] => 16857 [label] => 14 ) [9] => Array ( [total] => 67561.24973551929 [count] => 16953 [label] => 15 ) [10] => Array ( [total] => 53234.269776707515 [count] => 13534 [label] => 16 ) [11] => Array ( [total] => 32531.519873172045 [count] => 8319 [label] => 17 ) [12] => Array ( [total] => 19651.939934439957 [count] => 5046 [label] => 18 ) [13] => Array ( [total] => 16004.799943584949 [count] => 3962 [label] => 19 ) [14] => Array ( [total] => 6280.359964884818 [count] => 1540 [label] => 20 ) [15] => Array ( [total] => 499.8299940600991 [count] => 124 [label] => 21 ) )

Intended result if done via mysqli query

Array ( [0] => Array ( [0] => 3.700000047683716 [total] => 3.700000047683716 [1] => 1 [count] => 1 [2] => 9 [label] => 9 ) )

Problem in where using functions?

**Comment by peepsnet** [comment]
see Pull request https://github.com/msbatal/PHP-PDO-Database-Class/pull/4

**Comment by msbatal** [comment]
Repo updated and groupBy function parameters' orders are changed. Thank you @peepsnet !

**Comment by msbatal** [comment]
You're right. My earlier reply only addressed half of this, sorry for the premature "fixed."

The groupBy('column', 'DAYNAME') pattern I showed you is correct and works — and looking at your output, it's clearly working here too: those clean integer labels (2, 7, 8, 9 ... 21) are exactly what GROUP BY hour(createdAt) produces. If it were still grouping by the raw createdAt column, you wouldn't get tidy hour buckets like that.

The part that's actually still broken is the where() call:

`->where('createdAt', 'DATE_SUB(CURDATE(), INTERVAL 24 HOUR', '>=')`

where()'s value is always sent as a bound prepared-statement parameter, never interpreted as SQL. So this binds the literal string "DATE_SUB(CURDATE(), INTERVAL 24 HOUR" — it's not evaluated as a date expression at all. That's why the filter isn't doing anything: your query is aggregating your entire table history bucketed by hour-of-day, not just the last 24 hours. That also explains the counts, thousands per bucket, accumulated across every day you've ever recorded, not a single day's worth.

This is inherent to how prepared statements work (parameters are always data, never SQL), not something where() itself can be changed to support without reopening the exact kind of SQL-injection risk that's been closed elsewhere in this class.

Two correct ways to do what you want:

Recommended; compute the boundary in PHP and bind it as a normal value, no raw SQL needed at all:

```
$select = $db->select('sales_tbl', ['sum(total) as total', 'count(*) as count', 'hour(createdAt) as label'])
    ->where('createdAt', date('Y-m-d H:i:s', strtotime('-24 hours')), '>=')
    ->groupBy('createdAt', 'hour')
    ->run();
```

Or, if you specifically need the comparison computed on the DB side (e.g. for server-time consistency), there's now a whereRaw() method for exactly that:

```
$select = $db->select('sales_tbl', ['sum(total) as total', 'count(*) as count', 'hour(createdAt) as label'])
    ->whereRaw('createdAt >= DATE_SUB(CURDATE(), INTERVAL 24 HOUR)')
    ->groupBy('createdAt', 'hour')
    ->run();
```

(Same caveat as any raw-SQL escape hatch in this class: never put user input into that string.)

Either of these should match the mysqli result you posted. Let me know if it doesn't.
